In [1]:
import numpy as np

In [2]:
np.__version__

'1.20.2'

In [3]:
array = np.arange(100)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [4]:
np.arange(2,10,2) #easy way to remember is Start, Stop & Step

array([2, 4, 6, 8])

In [5]:
arr = np.arange(11)
np.append(arr, [9,10])

np.sort(arr)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.delete(arr, 1)

array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
np.sort(arr)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
multi_list = [[0,1,2,3,4], [5,6,7,8,9]]
np.array(multi_list)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
values = [
    ('Arthur', 1.8, 41), 
    ('Lancelot', 1.9,38),
    ('Garalh', 1.7,38)
    ]
values

[('Arthur', 1.8, 41), ('Lancelot', 1.9, 38), ('Garalh', 1.7, 38)]

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.ones(2)

array([1., 1.])

In [12]:
np.empty(3)

array([8.71588390e-312, 0.00000000e+000, 8.70018274e-312])

In [13]:
a=np.arange(6)
b=a.reshape(2,3)
c=b.reshape(3,2)
print(c)

[[0 1]
 [2 3]
 [4 5]]


In [14]:
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [15]:
data = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
data

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
print(data[data>=5])
print(data[data%2==0])

[ 5  6  7  8  9 10 11 12]
[ 2  4  6  8 10 12]


In [17]:
arr = np.array([[1,2,3,4,5,6,7,8,9], [10,11,12,13,14]])

C:\Users\HAIKAL~1\AppData\Local\Temp/ipykernel_8132/3419065835.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array([[1,2,3,4,5,6,7,8,9], [10,11,12,13,14]])


In [18]:
print(np.hsplit(arr, 2))

[array([list([1, 2, 3, 4, 5, 6, 7, 8, 9])], dtype=object), array([list([10, 11, 12, 13, 14])], dtype=object)]
